version: "3"
services:
  backend:
    build: ./backend
    image: deadlysin7/passportvault-backend:latest
    restart: always
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    image: deadlysin7/passportvault-frontend:latest
    environment:
      - VITE_BACKEND_URL=https://reimagined-fishstick-5rg9prvq6pp3pp66-8000.app.github.dev
    depends_on:
      - backend
    ports:
      - "5173:5173"
