services:
  backend:
    build: ./backend
    image: deadlysin7/passportvault-backend:latest
    restart: always
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    image: deadlysin7/passportvault-frontend:latest
    entrypoint: ["npm", "run", "preview"]
    environment:
      - VITE_BACKEND_URL=https://passportvault-backend-bhavesh-purohit-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
    depends_on:
      - backend
    ports:
      - "8080:8080"
