openapi: 3.0.0
info:
  version: "1.0.0"
  title: Members API
servers:
  - url: /
paths:
  /members:
    post:
      tags:
        - Members Routes
      summary: Create a new member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Member"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Member"
        "400":
          description: Bad request
    get:
      tags:
        - Members Routes
      summary: Retrieve all members
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Member"
        "500":
          description: Internal server error
  /members/{id}:
    get:
      tags:
        - Members Routes
      summary: Retrieve a single member by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Member"
        "404":
          description: Member not found
        "500":
          description: Internal server error
    put:
      tags:
        - Members Routes
      summary: Update a member by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Member"
      responses:
        "200":
          description: Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Member"
        "404":
          description: Member not found
        "400":
          description: Bad request
        "500":
          description: Internal server error
    delete:
      tags:
        - Members Routes
      summary: Delete a member by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Member"
        "404":
          description: Member not found
        "500":
          description: Internal server error
components:
  schemas:
    Member:
      type: object
      properties:
        memberType:
          type: string
        surname:
          type: string
        givenName:
          type: string
        birthDate:
          type: string
          format: date
        birthPlace:
          type: string
        nationality:
          type: string
        fatherName:
          type: object
          properties:
            surname:
              type: string
            givenName:
              type: string
        motherName:
          type: object
          properties:
            surname:
              type: string
            givenName:
              type: string
        spouseName:
          type: object
          properties:
            surname:
              type: string
            givenName:
              type: string
        education:
          type: object
          properties:
            nameOfInstitute:
              type: string
            course:
              type: string
            yearFrom:
              type: integer
            yearTo:
              type: integer
        joiningDate:
          type: string
          format: date
        address:
          type: object
          properties:
            line1:
              type: string
            line2:
              type: string
            line3:
              type: string
        documents:
          type: object
          properties:
            identity:
              type: string
            memberCertificate:
              type: string
            other:
              type: object
        otherInfo:
          type: object
