openapi: 3.0.0
info:
  version: "1.0.0"
  title: Passport API
servers:
  - url: /
paths:
  /passports:
    post:
      tags:
        - Passport Routes
      summary: Create a new passport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Passport"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Passport"
        "400":
          description: Bad request
    get:
      tags:
        - Passport Routes
      summary: Retrieve all passports
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Passport"
        "500":
          description: Internal server error
  /passports/{id}:
    get:
      tags:
        - Passport Routes
      summary: Retrieve a single passport by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Passport"
        "404":
          description: Passport not found
        "500":
          description: Internal server error
    put:
      tags:
        - Passport Routes
      summary: Update a passport by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Passport"
      responses:
        "200":
          description: Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Passport"
        "404":
          description: Passport not found
        "400":
          description: Bad request
        "500":
          description: Internal server error
    delete:
      tags:
        - Passport Routes
      summary: Delete a passport by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Passport"
        "404":
          description: Passport not found
        "500":
          description: Internal server error
components:
  schemas:
    Passport:
      type: object
      properties:
        parentMember_id:
          type: string
        country:
          type: string
        passportNo:
          type: string
        dateOfIssue:
          type: string
          format: date
        dateOfExpiry:
          type: string
          format: date
        placeOfIssue:
          type: string
        fileNo:
          type: string
        previousPassportNo:
          type: string
        previousPassportDateOfIssue:
          type: string
          format: date
        previousPassportPlaceOfIssue:
          type: string
        documents:
          type: object
          properties:
            coverPage:
              type: string
            firstPage:
              type: string
            lastPage:
              type: string
            pdf:
              type: string
        otherInfo:
          type: object
