swagger: "2.0"
info:
  version: "1.0.0"
  title: Passport API
basePath: /
schemes:
  - http
tags:
  - name: Passport Routes
    description: Endpoints for managing passports
paths:
  /passports:
    post:
      tags:
        - Passport Routes
      summary: Create a new passport
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Passport object
          required: true
          schema:
            $ref: "#/definitions/Passport"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/Passport"
        400:
          description: Bad request
    get:
      tags:
        - Passport Routes
      summary: Retrieve all passports
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Passport"
        500:
          description: Internal server error
  /passports/{id}:
    get:
      tags:
        - Passport Routes
      summary: Retrieve a single passport by ID
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Passport"
        404:
          description: Passport not found
        500:
          description: Internal server error
    put:
      tags:
        - Passport Routes
      summary: Update a passport by ID
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: body
          name: body
          description: Passport object
          required: true
          schema:
            $ref: "#/definitions/Passport"
      responses:
        200:
          description: Updated
          schema:
            $ref: "#/definitions/Passport"
        404:
          description: Passport not found
        400:
          description: Bad request
        500:
          description: Internal server error
    delete:
      tags:
        - Passport Routes
      summary: Delete a passport by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        200:
          description: Deleted
          schema:
            $ref: "#/definitions/Passport"
        404:
          description: Passport not found
        500:
          description: Internal server error
definitions:
  Passport:
    type: object
    properties:
      parentMember_id:
        type: string
      country:
        type: string
      passportNo:
        type: string
      dateOfIssue:
        type: string
        format: date
      dateOfExpiry:
        type: string
        format: date
      placeOfIssue:
        type: string
      fileNo:
        type: string
      previousPassportNo:
        type: string
      previousPassportDateOfIssue:
        type: string
        format: date
      previousPassportPlaceOfIssue:
        type: string
      documents:
        type: object
        properties:
          coverPage:
            type: string
          firstPage:
            type: string
          lastPage:
            type: string
          pdf:
            type: string
      otherInfo:
        type: object
