openapi: 3.0.0
info:
  version: "1.0.0"
  title: Travel Detail API
tags:
  - name: Travel Detail
    description: Endpoints for managing travel details
paths:
  /travel-details:
    post:
      tags:
        - Travel Detail
      summary: Create a new travel detail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TravelDetail"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TravelDetail"
        "400":
          description: Bad request
    get:
      tags:
        - Travel Detail
      summary: Retrieve all travel details
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TravelDetail"
        "500":
          description: Internal server error
  /travel-details/{id}:
    get:
      tags:
        - Travel Detail
      summary: Retrieve a single travel detail by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TravelDetail"
        "404":
          description: Travel detail not found
        "500":
          description: Internal server error
    put:
      tags:
        - Travel Detail
      summary: Update a travel detail by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TravelDetail"
      responses:
        "200":
          description: Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TravelDetail"
        "404":
          description: Travel detail not found
        "400":
          description: Bad request
        "500":
          description: Internal server error
    delete:
      tags:
        - Travel Detail
      summary: Delete a travel detail by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TravelDetail"
        "404":
          description: Travel detail not found
        "500":
          description: Internal server error
components:
  schemas:
    TravelDetail:
      type: object
      properties:
        _id:
          type: string
        parentVisa_id:
          type: string
        flightNo:
          type: string
        departureAirport:
          type: string
        arrivalAirport:
          type: string
        transits:
          type: array
          items:
            type: string
        documents:
          type: object
          properties:
            coverPage:
              type: string
            firstPage:
              type: string
            lastPage:
              type: string
            pdf:
              type: string
        otherInfo:
          type: object
