openapi: 3.0.0
info:
  version: "1.0.0"
  title: Visa API
servers:
  - url: /
paths:
  /visas:
    post:
      tags:
        - Visa Routes
      summary: Create a new visa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Visa"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Visa"
        "400":
          description: Bad request
    get:
      tags:
        - Visa Routes
      summary: Retrieve all visas
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Visa"
        "500":
          description: Internal server error
  /visas/{id}:
    get:
      tags:
        - Visa Routes
      summary: Retrieve a single visa by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Visa"
        "404":
          description: Visa not found
        "500":
          description: Internal server error
    put:
      tags:
        - Visa Routes
      summary: Update a visa by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Visa"
      responses:
        "200":
          description: Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Visa"
        "404":
          description: Visa not found
        "400":
          description: Bad request
        "500":
          description: Internal server error
    delete:
      tags:
        - Visa Routes
      summary: Delete a visa by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Visa"
        "404":
          description: Visa not found
        "500":
          description: Internal server error
components:
  schemas:
    Visa:
      type: object
      properties:
        parentPassport_id:
          type: string
        passportNo:
          type: string
        country:
          type: string
        visaType:
          type: string
        category:
          type: string
        noOfEntry:
          type: integer
        visaNo:
          type: string
        validFrom:
          type: string
          format: date
        validUntil:
          type: string
          format: date
        duration:
          type: integer
        annotation:
          type: string
        visaApplication_id:
          type: string
        documents:
          type: object
          properties:
            coverPage:
              type: string
            firstPage:
              type: string
            lastPage:
              type: string
            pdf:
              type: string
        otherInfo:
          type: object
