swagger: "2.0"
info:
  version: "1.0.0"
  title: Visa API
basePath: /
schemes:
  - http
tags:
  - name: Visa Routes
    description: Endpoints for managing visas
paths:
  /visas:
    post:
      tags:
        - Visa Routes
      summary: Create a new visa
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Visa object
          required: true
          schema:
            $ref: "#/definitions/Visa"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/Visa"
        400:
          description: Bad request
    get:
      tags:
        - Visa Routes
      summary: Retrieve all visas
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Visa"
        500:
          description: Internal server error
  /visas/{id}:
    get:
      tags:
        - Visa Routes
      summary: Retrieve a single visa by ID
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Visa"
        404:
          description: Visa not found
        500:
          description: Internal server error
    put:
      tags:
        - Visa Routes
      summary: Update a visa by ID
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - in: body
          name: body
          description: Visa object
          required: true
          schema:
            $ref: "#/definitions/Visa"
      responses:
        200:
          description: Updated
          schema:
            $ref: "#/definitions/Visa"
        404:
          description: Visa not found
        400:
          description: Bad request
        500:
          description: Internal server error
    delete:
      tags:
        - Visa Routes
      summary: Delete a visa by ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        200:
          description: Deleted
          schema:
            $ref: "#/definitions/Visa"
        404:
          description: Visa not found
        500:
          description: Internal server error
definitions:
  Visa:
    type: object
    properties:
      parentPassport_id:
        type: string
      passportNo:
        type: string
      country:
        type: string
      visaType:
        type: string
      category:
        type: string
      noOfEntry:
        type: integer
      visaNo:
        type: string
      validFrom:
        type: string
        format: date
      validUntil:
        type: string
        format: date
      duration:
        type: integer
      annotation:
        type: string
      visaApplication_id:
        type: string
      documents:
        type: object
        properties:
          coverPage:
            type: string
          firstPage:
            type: string
          lastPage:
            type: string
          pdf:
            type: string
      otherInfo:
        type: object
