swagger: '2.0'
info:
  version: '1.0.0'
  title: Passport API
  description: API for managing passports
tags:
  - name: Passports
    description: Operations about passports
paths:
  /passports:
    post:
      tags:
        - Passports
      summary: Create a new passport
      operationId: createPassport
      parameters:
        - in: body
          name: body
          description: Passport object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Passport'
      responses:
        '201':
          description: Passport created
        '400':
          description: Invalid input
    get:
      tags:
        - Passports
      summary: Get all passports
      operationId: getPassports
      responses:
        '200':
          description: Successful operation
        '500':
          description: Internal server error
  /passports/{id}:
    get:
      tags:
        - Passports
      summary: Get a passport by ID
      operationId: getPassport
      parameters:
        - in: path
          name: id
          description: ID of passport to return
          required: true
          type: string
      responses:
        '200':
          description: Successful operation
        '404':
          description: Passport not found
        '500':
          description: Internal server error
    put:
      tags:
        - Passports
      summary: Update a passport
      operationId: updatePassport
      parameters:
        - in: path
          name: id
          description: ID of passport to update
          required: true
          type: string
        - in: body
          name: body
          description: Passport object that needs to be updated
          required: true
          schema:
            $ref: '#/definitions/Passport'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '404':
          description: Passport not found
    delete:
      tags:
        - Passports
      summary: Delete a passport
      operationId: deletePassport
      parameters:
        - in: path
          name: id
          description: ID of passport to delete
          required: true
          type: string
      responses:
        '200':
          description: Successful operation
        '404':
          description: Passport not found
        '500':
          description: Internal server error
definitions:
  Passport:
    type: object
    properties:
      passportNumber:
        type: string
        description: The passport number
      issueDate:
        type: string
        format: date
        description: The date when the passport was issued
      expiryDate:
        type: string
        format: date
        description: The date when the passport will expire
      nationality:
        type: string
        description: The nationality of the passport holder
      holderName:
        type: string
        description: The name of the passport holder
    required:
      - passportNumber
      - issueDate
      - expiryDate
      - nationality
      - holderName